// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using GTSCustomerAPI.Infrastructure.Data;

#nullable disable

namespace GTSCustomerAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607210926_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("GTSCustomerAPI.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");

                    b.Property<string>("Addr1").HasColumnType("nvarchar(max)");

                    b.Property<string>("Addr2").HasColumnType("nvarchar(max)");

                    b.Property<string>("Account").HasColumnType("nvarchar(max)");

                    b.Property<string>("City").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact").HasColumnType("nvarchar(max)");
                });
        }
    }
}
